### ISSUE TITLE
font-family attribute

### ISSUE THREAD

**Issue by mpaiva** [MaxBazarov/design-system#1]
Congrats on the plugin, it works beautifully. Any plans to include the font-family attribute soon?

**Comment by MaxBazarov** [comment]
Thanks!

Did you try “font-face” rule?

**Comment by mpaiva** [comment]
that did it! thanks! 

BTW: I have a plugin that export tokens from sketch:
https://github.com/mpaiva/tokenizer

I'd love to collaborate on a full solution to export the JSON file.
